FROM python:3.10

RUN pip install --upgrade pip

ENV DB_USER postgres.uvldxnsupxkpwzeaeihh
ENV DB_PASSWORD 31Evu7yB!Q=[
ENV DB_NAME postgres
ENV DB_PORT 5432
ENV DB_HOST aws-0-us-east-1.pooler.supabase.com
